config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    collection do
      post 'confirm'
      get 'confirm'

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
  class PostsController < ApplicationController
    def new
      @post = Post.new
      @post.content = params[:content] if params[:content].present?
    end
  
    def create
      if params[:back]
        @post = Post.new(content: params[:content])
        render :new
      else
        @post = Post.new(post_params)
        if @post.save
          redirect_to posts_path, notice: "Post created!"
        else
          render :new
        end
      end
    end
  

  def show
    @post = Post.find(params[:id])
    if @post.nil?
    end
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

  if @post.update(post_params)
    redirect_to @post
  else
    render 'edit'
  end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to posts_path
end

def confirm
  if params[:post].present?
  @post = Post.new(post_params)
  if @post.invalid?
    render :confirm
  end
else
  @post = Post.new
  render :new
end
end

private

def post_params
    params.require(:post).permit(:content)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tsubuyaki002</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>つぶやき。</h1>

    </header>
      <div class ="container">
      <%= yield %>
      </div>

    <footer>
      <p>Copyright &copy; 2023 Tsubuyaki002. All rights reserved.</p>
    </footer>
    
  </body>
</html>

app/views/posts/confirm.html.erb
<h1>以下の内容で、送信する。</h1>

<p>あなたは次の内容を投稿しようとしています:</p>
<p><%= @post.content %></p>

<%= form_with model: @post, local: true do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "投稿" %>
<% end %>

<%= form_with url: new_post_path, method: :get, local: true do %>
  <%= hidden_field_tag :content, @post.content %>
  <%= submit_tag "戻る" %>
<% end %>

app/views/posts/edit.html.erb
<h1>つぶやきを変更できるよ</h1>

<%= form_with model: @post do |form| %>
<div>
<%= form.label :content, '投稿内容', class: 'top-label' %>
<%= form.text_area :content, rows: 5, cols: 50, class: "fixed-size" %>
</div>

<div class="submit-button">
  <%= form.submit '編集完了'%>
</div>
<% end %>

<%= link_to '戻る', posts_path %>

app/views/posts/index.html.erb
<h1>過去のつぶやき</h1>
<br>
<table>
  <tr>
    <th>こんなことつぶやいてたよ</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <td><%= link_to '閲覧', post_path(post) %></td>
    <td><%= link_to '編集', edit_post_path(post) %></td>
    <td><%= link_to '削除', post, method: :delete, data: { confirm: '本当に消しちゃうの?' } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to '新しいことをつぶやこう', new_post_path %>

app/views/posts/new.html.erb
<%= form_with(model: @post, url: confirm_posts_path, method: :post) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div>
    <%= form.label :content, '今はどんな気分？' %>
    </div>
    <div>
    <%= form.text_area :content, rows: 5, cols: 50 %>
    </div>
  </div>

  <div class="actions form-group">
    <%= form.submit '投稿する' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<p>
  <strong>投稿確認:</strong>
</p>
<p>
  <%= @post.content %>
</p>
<p>
  <%= link_to '編集' ,edit_post_path(@post) %>
  <%= link_to '過去のつぶやき', posts_path %>
</p>